description: Helm chart for the HMCTS fees register admin frontend
name: fees-register-frontend
home: https://github.com/hmcts/ccfr-fees-register-admin-web
version: 0.0.4
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
