description: Helm chart for the HMCTS fees register admin frontend
name: fees-register-frontend
home: https://github.com/hmcts/ccfr-fees-register-admin-web
version: 0.0.1
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
idam-pr:
  service:
    name: fees-register-admin
    redirect_uri: https://${SERVICE_FQDN}/callback # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
