apiVersion: v1
appVersion: "1.0"
description: Helm chart for the HMCTS fees register admin frontend
name: fees-register-frontend
home: https://github.com/hmcts/ccfr-fees-register-admin-web
version: 0.0.5
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
idam-pr:
  service:
    name: fees-register-admin # this is the label (name) of the service as configured in IDAM. If unsure, see below.
    redirect_uri: https://${SERVICE_FQDN}/oauth2/callback # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
