apiVersion: v2
appVersion: "2.0"
description: Helm chart for the HMCTS fees register admin frontend
name: fees-register-frontend
home: https://github.com/hmcts/ccfr-fees-register-admin-web
version: 0.1.3
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'
  - name: idam-pr
    version: ~2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
