apiVersion: v1
appVersion: "1.0"
description: Helm chart for the HMCTS fees register admin frontend
name: fees-register-frontend
home: https://github.com/hmcts/ccfr-fees-register-admin-web
version: 0.1.2
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
