dependencies:
  - name: fees-register-api
    version: 0.0.1
    repository: '@hmcts'
  - name: nodejs
    version: 0.0.11
    repository: '@hmcts'
  - name: idam-pr
    version: ~1.0.0
    repository: '@hmcts'
    tags:
    - idam-pr
