dependencies:
  - name: fees-register-api
    version: ~0.0.4
    repository: '@hmcts'
  - name: nodejs
    version: 1.0.0
    repository: '@hmcts'
  - name: idam-pr
    version: ~1.0.0
    repository: '@hmcts'
    tags:
    - idam-pr
idam-pr:
  service:
    name: fees-register-admin # this is the label (name) of the service as configured in IDAM. If unsure, see below.
    redirect_uri: https://${SERVICE_FQDN}/oauth2/callback # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
