idam-pr:
  service:
    name: fees-register-admin
    redirect_uri: https://${SERVICE_FQDN}/oauth2/callback
nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
    IDAM_LOGIN_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
tags:
  idam-pr: true
