nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devmemoryRequests: 1024Mi
  devcpuRequests: 1000m
  devmemoryLimits: 1024Mi
  devcpuLimits: 1000m
  memoryRequests: 1024Mi
  cpuRequests: 1000m

