nodejs:
  environment:
    FEES_CLIENT_SECRET: ${FEES_CLIENT_SECRET}
    IDAM_API_URL: https://preprod-idamapi.reform.hmcts.net:3511
    IDAM_AUTHENTICATION_WEB_URL: https://idam.preprod.ccidam.reform.hmcts.net
    IDAM_LOGIN_WEB_URL: https://idam.preprod.ccidam.reform.hmcts.net/login

tags:
  - idam-pr
idam-pr:
  service:
    name: fees-register-admin
    redirect_uri: https://${SERVICE_FQDN}/callback # this is the application callback URL where IDAM will send back the authentication code. SERVICE_FQDN is injected by Jenkins.
