fees-register-api:
  releaseNameOverride: "{{ .Release.Name }}-fees-register-api"
  java:
    releaseNameOverride: "{{ .Release.Name }}-fees-register-api"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-fees-register-db:5432/fees_register"
      IDAM_CLIENT_BASE_URL: https://idam-api.aat.platform.hmcts.net  

nodejs:
  image: 'https://hmcts.azurecr.io/hmcts/fees-register-admin-web:latest'
  applicationPort: 3000
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - freg-idam-client-secret
  environment:
    REFORM_TEAM: ccpay
    REFORM_SERVICE_NAME: fees-register-frontend
    REFORM_ENVIRONMENT: preview
    NODE_ENV: production

    FEES_URL: "http://{{ .Release.Name }}-fees-register-api"

    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
    IDAM_LOGIN_WEB_URL: https://idam-web-public.aat.platform.hmcts.net/login
    FEES_CLIENT_ID: fees_admin_frontend
