nodejs:
  ingressHost: fees-register.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: ccpay
  memoryRequests: 1024Mi
  cpuRequests: 1000m
  memoryLimits: 2048Mi
  cpuLimits: 1500m
  devmemoryRequests: 1024Mi
  devcpuRequests: 1000m
  devmemoryLimits: 1024Mi
  devcpuLimits: 1000m
  readinessDelay: 45
  livenessDelay: 45
  keyVaults:
    ccpay:
      secrets:
        - freg-idam-client-secret
        - AppInsightsInstrumentationKey
  environment:
    NODE_ENV: production
    FEES_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_LOGIN_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login
    FEES_CLIENT_ID: fees_admin_frontend
idam-pr:
  enabled: false
