nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    ccpay:
      secrets: []
idam-pr:
  enabled: true
  redirect_uris:
    fees-register-admin:
      - https://${SERVICE_FQDN}/oauth2/callback
