language: node_js
node_js:
  - "node"
  - "8"
addons:
  apt:
    update: true
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn setup
  - yarn lint
  - yarn test
  - yarn test:routes
  - yarn test:a11y
  - yarn test:coverage-unit
after_success:
  - yarn test:codacy-upload
  - yarn test:codecov-upload
