apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${IMAGE_NAME}
        name: ${SERVICE_NAME}
        envFrom:
        - configMapRef:
            name: ${SERVICE_NAME}-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # This is the port your process is listening on in the container
        ports:
        - containerPort: 3000
          name: http
        imagePullPolicy: Always

# Azure Internal Loadbalancer.
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    # Make sure targetPort is the same as 'containerPort' above...
    targetPort: 3000
  selector:
    app: ${SERVICE_NAME}
