capacity = "2"
vault_section = "preprod"
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
authentication_web_url = "https://idam-web-public.aat.platform.hmcts.net"
external_host_name ="fees-register.aat.platform.hmcts.net"
