vault_section = "preprod"
capacity = "2"
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
authentication_web_url = "https://idam.preprod.ccidam.reform.hmcts.net"
external_host_name ="fees-register.demo.platform.hmcts.net"
