vault_section = "prod"
capacity = "2"
idam_api_url = "https://idam-api.platform.hmcts.net"
authentication_web_url = "https://www.idam.platform.hmcts.net"
external_host_name ="www.fees-register.platform.hmcts.net"
